settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: wosc-web # unique identifier
    name: Website
    description: 'Official World of SteelCraft Website' # default=empty
    url: 'https://worldofsteelcraft.tk/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: wosc-smp # unique identifier
    name: WoSC SMP Server
    url: 'https://api.mcsrvstat.us/bedrock/simple/smp.worldofsteelcraft.tk:25576' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: wosc-files # unique identifier
    name: WoSC SMP Server
    url: 'https://files.worldofsteelcraft.tk' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: wosc-links-1 # unique identifier
    name: Link Service 1
    url: 'https://wosc.tk/' # URL to fetch
    method: GET # default=GET
    expectStatus: 301 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: wosc-links-2 # unique identifier
    name: Link Service 2
    url: 'https://lnksvc2.wosc.tk/' # URL to fetch
    method: GET # default=GET
    expectStatus: 301 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
